export * from './REGEX_CHAR_SPECIAL';
export * from './REGEX_CNPJ';
export * from './REGEX_CPF_CNPJ';
export * from './REGEX_CPF';
export * from './REGEX_EMAIL';
export * from './REGEX_NUMBER';
export * from './REGEX_PHONE_BR';
export * from './REGEX_UPPER_CASE';
export * from './REGEX_URL';
